/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kamac8665
 */
public class FormAlgorithmDesign extends javax.swing.JFrame {

    /**
     * Creates new form FormAlgorithmDesign
     */
    public FormAlgorithmDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        factorialTitleLabel = new javax.swing.JLabel();
        primeNumberTitleLabel = new javax.swing.JLabel();
        fibonacciTitleLabel = new javax.swing.JLabel();
        factorialOutput = new javax.swing.JLabel();
        primeNumberOutput = new javax.swing.JLabel();
        fibonacciOutput = new javax.swing.JLabel();
        factorialButton = new javax.swing.JButton();
        primeNumberButton = new javax.swing.JButton();
        fibonacciButton = new javax.swing.JButton();
        factorialInput = new javax.swing.JTextField();
        primeNumberInput = new javax.swing.JTextField();
        fibonacciInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(204, 204, 255));

        titleLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        titleLabel.setText("--NUMBERS--");

        factorialTitleLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        factorialTitleLabel.setText("Enter a number and click the button to find the factorial:");

        primeNumberTitleLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        primeNumberTitleLabel.setText("Enter a number and click the button to determine whether or not it is a prime number:");

        fibonacciTitleLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        fibonacciTitleLabel.setText("Enter a number and click the button to see the corresponding Fibonacci Number:");

        factorialOutput.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        factorialOutput.setText("---");

        primeNumberOutput.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        primeNumberOutput.setText("---");

        fibonacciOutput.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        fibonacciOutput.setText("---");

        factorialButton.setText("Factorial");
        factorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialButtonActionPerformed(evt);
            }
        });

        primeNumberButton.setText("Prime");
        primeNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeNumberButtonActionPerformed(evt);
            }
        });

        fibonacciButton.setText("Fibonacci");
        fibonacciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibonacciButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(factorialInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(primeNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(fibonacciInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(factorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(factorialOutput))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(fibonacciButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fibonacciOutput))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(primeNumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(primeNumberOutput)))
                .addGap(168, 168, 168))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(titleLabel))
                    .addComponent(factorialTitleLabel)
                    .addComponent(primeNumberTitleLabel)
                    .addComponent(fibonacciTitleLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(32, 32, 32)
                .addComponent(factorialTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factorialOutput)
                    .addComponent(factorialButton)
                    .addComponent(factorialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(primeNumberTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeNumberOutput)
                    .addComponent(primeNumberButton)
                    .addComponent(primeNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(fibonacciTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fibonacciOutput)
                    .addComponent(fibonacciButton)
                    .addComponent(fibonacciInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialButtonActionPerformed
        int factorial;
        
        factorial = Integer.parseInt(factorialInput.getText());
        
        for(int i = factorial - 1; i >= 1; i = i - 1){
            factorial = factorial * i;
            i = i - 1;
        }
        factorialOutput.setText("" + factorial);
    }//GEN-LAST:event_factorialButtonActionPerformed

    private void primeNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeNumberButtonActionPerformed
        int userNum;
        int temp;
        boolean isPrime=true;
        
        
        userNum = Integer.parseInt(primeNumberInput.getText());
        
        for(int i = 2; i <= userNum / 2; i = i + 1)
        {
            temp = userNum % i;
            
            if(temp==0)
            {
                isPrime = false;
                break;
            }
        }    
        
        if(isPrime)
            {primeNumberOutput.setText(userNum + " is a prime number.");}
        else
            {primeNumberOutput.setText(userNum + " is not a prime number.");}
    }//GEN-LAST:event_primeNumberButtonActionPerformed

    
    public int fibonacciRecursive(int n) {
        if (n <= 1) {
            return n;
        }
        return fibonacciRecursive(n - 1) + fibonacciRecursive(n - 2);
    }
    
    private void fibonacciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibonacciButtonActionPerformed
        FormAlgorithmDesign fib = new FormAlgorithmDesign();
        
        int n;
        
        n = Integer.parseInt(fibonacciInput.getText());
        
        fibonacciOutput.setText("" + fib.fibonacciRecursive(n));
    }//GEN-LAST:event_fibonacciButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlgorithmDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton factorialButton;
    private javax.swing.JTextField factorialInput;
    private javax.swing.JLabel factorialOutput;
    private javax.swing.JLabel factorialTitleLabel;
    private javax.swing.JButton fibonacciButton;
    private javax.swing.JTextField fibonacciInput;
    private javax.swing.JLabel fibonacciOutput;
    private javax.swing.JLabel fibonacciTitleLabel;
    private javax.swing.JButton primeNumberButton;
    private javax.swing.JTextField primeNumberInput;
    private javax.swing.JLabel primeNumberOutput;
    private javax.swing.JLabel primeNumberTitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
